//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecocoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarbageRaport
    {
        public int RaportID { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public double GarbageAmount { get; set; }
        public int GarbageType { get; set; }
        public int Route { get; set; }
    
        public virtual GarbageType GarbageType1 { get; set; }
        public virtual Route Route1 { get; set; }
    }
}
