//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecocoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        public int RouteID { get; set; }
        public int TruckID { get; set; }
        public System.DateTime Date { get; set; }
        public int GarbageType { get; set; }
    
        public virtual GarbageType GarbageType1 { get; set; }
        public virtual Route Route { get; set; }
        public virtual Truck Truck { get; set; }
    }
}
