//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecocoon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseSmieciEntities : DbContext
    {
        public DatabaseSmieciEntities()
            : base("name=DatabaseSmieciEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_add_info> Users_add_info { get; set; }
        public virtual DbSet<GarbageType> GarbageType { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Truck> Truck { get; set; }
    }
}
