//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecocoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TruckID { get; set; }
        public int UserID { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Truck Truck { get; set; }
        public virtual Users Users { get; set; }
    }
}
