//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecocoon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_add_info
    {
        public int UserID { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public string Bank_tran_det { get; set; }
        public string Phone_num { get; set; }
        public string Domicile { get; set; }
        public bool Completed { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
